apiVersion: 1

datasources:
  - name: TeslaMate
    uid: TeslaMate
    type: influxdb
    url: http://influxdb:8086
    database: $INFLUXDB_DATABASE
    access: proxy
    basicAuth: false
    withCredentials: false
    isDefault: true
    editable: true
