{
 "title": "Charging Stats",
 "tags": [ "teslamate" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "car",
    "label": "Car",
    "query": "SHOW TAG VALUES FROM \"positions\" WITH KEY = \"vin\""
   }
  ]
 },
 "panels": [
  { "title": "Summary of this period", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of Charges",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"energy_added_wh\") AS \"Charges\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/"
    }
   ]
  },
  {
   "title": "Total Energy Added",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"energy_added_wh\")/1000 AS \"Energy\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Total Charging Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"cost\") AS \"Cost\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Avg Cost / kWh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"cost\")/sum(\"energy_added_wh\")*1000 AS \"Cost\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Top Charging Stations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "SELECT sum(\"energy_added_wh\")/1000 AS \"Energy kWh\", count(\"energy_added_wh\") AS \"Sessions\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0 GROUP BY \"geofence_name\""
    }
   ]
  },
  {
   "title": "Charge Level Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT mean(\"start_battery_level\") AS \"Start SOC\", mean(\"end_battery_level\") AS \"End SOC\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0 GROUP BY time($__interval) fill(previous)"
    }
   ]
  }
 ]
}