{
 "title": "Charge Details",
 "tags": [ "teslamate" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "charge",
    "label": "Charge",
    "query": "SHOW TAG VALUES FROM \"charging_sessions\" WITH KEY = \"charge_id\""
   }
  ]
 },
 "panels": [
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"cost\") AS \"Cost\" FROM \"charging_sessions\" WHERE \"charge_id\" = '$charge'"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"duration_seconds\") AS \"Duration\" FROM \"charging_sessions\" WHERE \"charge_id\" = '$charge'"
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"geofence_name\") AS \"Location\" FROM \"charging_sessions\" WHERE \"charge_id\" = '$charge'"
    }
   ]
  },
  {
   "title": "Energy Added",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"energy_added_wh\")/1000 AS \"Energy\" FROM \"charging_sessions\" WHERE \"charge_id\" = '$charge'"
    }
   ]
  },
  {
   "title": "Location Map",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "query": "SELECT last(\"start_lat\") AS \"latitude\", last(\"start_lng\") AS \"longitude\" FROM \"charging_sessions\" WHERE \"charge_id\" = '$charge'"
    }
   ]
  },
  {
   "title": "SOC Added",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"end_battery_level\") - last(\"start_battery_level\") AS \"Added\" FROM \"charging_sessions\" WHERE \"charge_id\" = '$charge'"
    }
   ]
  },
  {
   "title": "Charge Curve",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT mean(\"battery_level\") AS \"Battery %\", mean(\"power\")/1000 AS \"Power kW\", mean(\"energy_added\") AS \"Added kWh\" FROM \"charge_readings\" WHERE \"charge_id\" = '$charge' GROUP BY time($__interval) fill(previous)"
    }
   ]
  }
 ]
}