{
 "title": "Charges",
 "tags": [ "teslamate" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "car",
    "label": "Car",
    "query": "SHOW TAG VALUES FROM \"positions\" WITH KEY = \"vin\""
   }
  ]
 },
 "panels": [
  { "title": "Summary of this period", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of Charges",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"energy_added_wh\") AS \"Charges\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/"
    }
   ]
  },
  {
   "title": "Energy Added",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"energy_added_wh\")/1000 AS \"Energy\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"cost\") AS \"Cost\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Avg Cost / kWh",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"cost\")/sum(\"energy_added_wh\")*1000 AS \"Cost\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Charges",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "SELECT \"geofence_name\" AS \"Location\", \"energy_added_wh\"/1000 AS \"Energy kWh\", \"duration_seconds\"/60 AS \"Duration min\", \"cost\" AS \"Cost\", \"start_battery_level\" AS \"Start %\", \"end_battery_level\" AS \"End %\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Energy per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "SELECT sum(\"energy_added_wh\")/1000 AS \"Energy\" FROM \"charging_sessions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0 GROUP BY time(1d) fill(0)"
    }
   ]
  },
  {
   "title": "Charging Power by Session",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "SELECT mean(\"power\")/1000 AS \"Power\" FROM \"charge_readings\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ GROUP BY time($__interval), \"charge_id\""
    }
   ]
  }
 ]
}