{
 "title": "Drive Details",
 "tags": [ "teslamate" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "drive",
    "label": "Drive",
    "query": "SHOW TAG VALUES FROM \"drives\" WITH KEY = \"drive_id\""
   },
   {
    "name": "dstart",
    "query": "SELECT \"start_time\" FROM \"drives\" WHERE \"drive_id\" = '$drive'"
   },
   {
    "name": "dend",
    "query": "SELECT \"end_time\" FROM \"drives\" WHERE \"drive_id\" = '$drive'"
   },
   { "name": "length_unit", "label": "Length", "query": "km : 1 , mi : 0.621371" }
  ]
 },
 "panels": [
  {
   "title": "Drive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT mean(\"speed\")*1.60934*$length_unit AS \"Speed [${length_unit:text}/h]\", mean(\"power\")/1000 AS \"Power kW\", mean(\"battery_level\") AS \"Battery %\", mean(\"ideal_battery_range_km\")*$length_unit AS \"Ideal [${length_unit:text}]\" FROM \"positions\" WHERE time >= '$dstart' AND time <= '$dend' GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Route",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"latitude\", \"longitude\" FROM \"positions\" WHERE time >= '$dstart' AND time <= '$dend' AND \"latitude\" > -90 ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Elevation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "SELECT mean(\"elevation\") AS \"Elevation\" FROM \"positions\" WHERE time >= '$dstart' AND time <= '$dend' GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT mean(\"outside_temp\") AS \"Outside\", mean(\"inside_temp\") AS \"Inside\" FROM \"positions\" WHERE time >= '$dstart' AND time <= '$dend' GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"distance_meters\")/1000*$length_unit AS \"Distance [${length_unit:text}]\" FROM \"drives\" WHERE \"drive_id\" = '$drive'"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"duration_seconds\") AS \"Duration\" FROM \"drives\" WHERE \"drive_id\" = '$drive'"
    }
   ]
  },
  {
   "title": "Energy Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"energy_used_wh\")/1000 AS \"Energy\" FROM \"drives\" WHERE \"drive_id\" = '$drive'"
    }
   ]
  },
  {
   "title": "Avg Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"average_speed\")*1.60934*$length_unit AS \"Speed [${length_unit:text}/h]\" FROM \"drives\" WHERE \"drive_id\" = '$drive'"
    }
   ]
  },
  {
   "title": "Route",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"geofence_enter\") AS \"From\", last(\"geofence_exit\") AS \"To\" FROM \"drives\" WHERE \"drive_id\" = '$drive'"
    }
   ]
  }
 ]
}