{
 "title": "Drive Stats",
 "tags": [ "teslamate" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "car",
    "label": "Car",
    "query": "SHOW TAG VALUES FROM \"positions\" WITH KEY = \"vin\""
   },
   { "name": "length_unit", "label": "Length", "query": "km : 1 , mi : 0.621371" }
  ]
 },
 "panels": [
  {
   "title": "# of Drives",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"distance_meters\") AS \"Drives\" FROM \"drives\" WHERE $timeFilter AND \"vin\" =~ /^$car$/"
    }
   ]
  },
  {
   "title": "Total Distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"distance_meters\")/1000*$length_unit AS \"Distance [${length_unit:text}]\" FROM \"drives\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Median Drive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT percentile(\"distance_meters\", 50)/1000*$length_unit AS \"Distance [${length_unit:text}]\" FROM \"drives\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Max Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"max_speed\")*1.60934*$length_unit AS \"Speed [${length_unit:text}/h]\" FROM \"drives\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Energy Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"energy_used_wh\")/1000 AS \"Energy\" FROM \"drives\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Speed Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT \"speed\"*1.60934*$length_unit AS \"Speed [${length_unit:text}/h]\" FROM \"positions\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"speed\" > 1"
    }
   ]
  },
  {
   "title": "Top Destinations",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"distance_meters\") AS \"Visits\" FROM \"drives\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0 GROUP BY \"geofence_exit\""
    }
   ]
  }
 ]
}