{
 "title": "Efficiency",
 "tags": [ "teslamate" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "car",
    "label": "Car",
    "query": "SHOW TAG VALUES FROM \"positions\" WITH KEY = \"vin\""
   },
   { "name": "length_unit", "label": "Length", "query": "km : *1 , mi : *0.621371" }
  ]
 },
 "panels": [
  {
   "title": "Avg Consumption, Wh/km (gross)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"energy_used_wh\")/sum(\"distance_meters\")*1000 AS \"Consumption\" FROM \"drives\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0 AND \"distance_meters\" > 100"
    }
   ]
  },
  {
   "title": "Logged Distance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"distance_meters\")/1000$length_unit AS \"Distance [${length_unit:text}]\" FROM \"drives\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0"
    }
   ]
  },
  {
   "title": "Consumption per Drive, Wh/km",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT \"energy_used_wh\"/\"distance_meters\"*1000 AS \"Wh/km\" FROM \"drives\" WHERE $timeFilter AND \"vin\" =~ /^$car$/ AND \"duration_seconds\" >= 0 AND \"distance_meters\" > 100"
    }
   ]
  }
 ]
}