{
 "title": "States",
 "tags": [ "teslamate" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "car",
    "label": "Car",
    "query": "SHOW TAG VALUES FROM \"positions\" WITH KEY = \"vin\""
   }
  ]
 },
 "panels": [
  {
   "title": "Current State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"state\") AS \"State\" FROM \"states\" WHERE $timeFilter AND \"vin\" =~ /^$car$/"
    }
   ]
  },
  {
   "title": "States",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "SELECT \"state\" FROM \"states\" WHERE $timeFilter AND \"vin\" =~ /^$car$/"
    }
   ]
  },
  {
   "title": "State Changes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"state\") AS \"Changes\" FROM \"states\" WHERE $timeFilter AND \"vin\" =~ /^$car$/"
    }
   ]
  }
 ]
}